### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by Surbyte** [devxplained/MAX3010x-Sensor-Library#1]
I try to compile each examples on ESP8266 but i receive this error. ESP32 similar problem.
Works fine with Arduino UNO/NANO/MEGA.
I am using IDE 1.8.14 or PlatformIO. 

```
surby\Documents\Arduino\libraries\MAX3010x_Sensor_Library\src/MAX30101.h:8,
                 from C:\Users\surby\Documents\Arduino\libraries\MAX3010x_Sensor_Library\src/MAX3010x.h:23,
                 from C:\Users\surby\Documents\Arduino\libraries\MAX3010x_Sensor_Library\examples\MAX30105PulseoximeterMultiLED\MAX30105PulseoximeterMultiLED.ino:1:
C:\Users\surby\Documents\Arduino\libraries\MAX3010x_Sensor_Library\src/MAX3010x_multiLed_core.h: In member function 'bool MAX3010xMultiLed<MAX3010xImpl, MAX3010xSample>::setMultiLedConfigurationInternal(uint8_t, uint8_t*)':
C:\Users\surby\Documents\Arduino\libraries\MAX3010x_Sensor_Library\src/MAX3010x_multiLed_core.h:85:12: error: there are no arguments to 'clearFIFO' that depend on a template parameter, so a declaration of 'clearFIFO' must be available [-fpermissive]
   85 |     return clearFIFO();

```
Any suggestion will be appreciatte!

**Comment by devxplained** [comment]
It seems to be an issue specific to the compiler version/options used for these platforms. I can reproduce this for the Arduino Due as well. I'll look into it and update the library.

**Comment by devxplained** [comment]
I submitted some fixes that solve the problem for me. Can you check if that fixes it for you by manually installing the attached Library (unzip it and copy it to your `Arduino/libraries` folder). If so I will release a new library version and publish it to the Arduino and the Platform IO repository.

[MAX3010x-Sensor-Library-compilation-fixes.zip](https://github.com/devxplained/MAX3010x-Sensor-Library/files/8647563/MAX3010x-Sensor-Library-compilation-fixes.zip)

**Comment by Surbyte** [comment]
The sketch works Ok.
I am trying to understand outputs comparing with Sparkfun examples.
Thanks!!.

**Comment by devxplained** [comment]
Glad I could help. If you need more information on how to use the library or how to detect heart beats and do pulse oximetry, you might find it helpful to read the corresponding tutorial series:
- Part 1: Acquiring data - https://devxplained.eu/en/blog/max3010x-pulse-oximeter-modules-part-1
- Part 2: Simpler detection algorithm - https://devxplained.eu/en/blog/max3010x-pulse-oximeter-modules-part-2
- Part 3: More advanced heart rate algorithm - https://devxplained.eu/en/blog/max3010x-pulse-oximeter-modules-part-3
- Part 4: SpO2 Measurements - https://devxplained.eu/en/blog/max3010x-pulse-oximeter-modules-part-4

Please note, that not all sensors support all LEDs. The MAX30105PulseoximeterMultiLED example you tried is for the MAX30105. The MAX30102 e.g. has no green LED. It is so similar that it will still work, however, the last two values will contain garbage. Just replace MAX30105 with MAX30102 to write code specific for this sensor.

**Comment by Technerder** [comment]
Hi, I just recently found this library (only one that worked for my MAX30101!)/issue and wanted to test out the example code in part 4 but I was unable to get the code for the `filters.h` file as the button your website (tested with Firefox and Chrome) doesn't seem to work, also are there any plans to include the examples from your blog into the examples that are shipped with the Arduino library (mainly for detecting heart rate and SpO2 values)?

**Comment by devxplained** [comment]
I opened a separate issue for this. The website should work now.

**Comment by Technerder** [comment]
Awesome, thank you so much!
