### ISSUE TITLE
Provide SpO2 Measurement Example

### ISSUE THREAD

**Issue by devxplained** [devxplained/MAX3010x-Sensor-Library#3]
Hi, I just recently found this library (only one that worked for my MAX30101!)/issue and wanted to test out the example code in part 4 but I was unable to get the code for the `filters.h` file as the button your website (tested with Firefox and Chrome) doesn't seem to work, also are there any plans to include the examples from your blog into the examples that are shipped with the Arduino library (mainly for detecting heart rate and SpO2 values)?

_Originally posted by @Technerder in https://github.com/devxplained/MAX3010x-Sensor-Library/issues/1#issuecomment-1129237367_

**Comment by devxplained** [comment]
Examples have been added and will be available in the new library version tomorrow.

**Comment by Technerder** [comment]
Awesome, can't wait :)
